### ISSUE TITLE
commands for linux/mac are wrong

### ISSUE THREAD

**Issue by jredfox** [Lartsch/java-selfconsole#4]
the commands uses substring(1) on windows but, not mac and linux when it's the same command for all three

**Comment by Lartsch** [comment]
Hi @jredfox,

you are right with all the issues you mentioned! This was far from perfect and pretty much an on-demand snippet for another project.

I see you made a greatly optimized version which I will link from this repos readme.

Thanks and stay healty!

**Comment by Lartsch** [comment]
https://github.com/jredfox/SelfCommandPrompt
