### ISSUE TITLE
Does not seem to open a window - MacOS Sierra

### ISSUE THREAD

**Issue by UltraBlackLinux** [Lartsch/java-selfconsole#5]
Hey, there,
I recently added this to a project of mine, but I have a problem: It doesn't open a terminal window on mac os Sierra. (You seem to only execute bash, not open a Terminal window).

I hope you are able to fix this, it is a great project, you did here ;)
Thanks alot!

**Comment by Lartsch** [comment]
Hi @UltraBlackLinux,

you are right about the mac commands, these were untested as I don't own a mac and did not want to setup a VM or similar.

I will not add the fix (this snippet was more like a on-demand thing for another project which I just decided to make public) but you can head over to https://github.com/jredfox/SelfCommandPrompt who made a far better version!

Stay healty!

**Comment by Lartsch** [comment]
https://github.com/jredfox/SelfCommandPrompt
